 datid  |      datname       | pid  | usesysid | usename  | application_name | client_addr | client_hostname | client_port |         backend_start         |          xact_start           |          query_start          |         state_change          | wait_event_type | wait_event | state  | backend_xid | backend_xmin |                 query                 |  backend_type  
--------+--------------------+------+----------+----------+------------------+-------------+-----------------+-------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-----------------+------------+--------+-------------+--------------+---------------------------------------+----------------
        |                    |  122 |          |          |                  |             |                 |             |                               |                               |                               |                               |                 |            |        |             |              | <insufficient privilege>              | 
        |                    |  124 |       10 | postgres |                  |             |                 |             |                               |                               |                               |                               |                 |            |        |             |              | <insufficient privilege>              | 
 106496 | deveto_development | 1906 |    16384 | ricardo  | ./bin/rails      |             |                 |          -1 | 2020-09-07 16:51:56.662932+01 |                               | 2020-09-07 16:51:56.76665+01  | 2020-09-07 16:51:56.766679+01 | Client          | ClientRead | idle   |             |              | SELECT "movies"."title" FROM "movies" | client backend
 106496 | deveto_development | 2426 |    16384 | ricardo  | psql             |             |                 |          -1 | 2020-09-07 16:55:11.722739+01 | 2020-09-07 16:55:22.344861+01 | 2020-09-07 16:55:22.344861+01 | 2020-09-07 16:55:22.344865+01 |                 |            | active |             |        10176 | SELECT * FROM pg_stat_activity;       | client backend
        |                    |  120 |          |          |                  |             |                 |             |                               |                               |                               |                               |                 |            |        |             |              | <insufficient privilege>              | 
        |                    |  119 |          |          |                  |             |                 |             |                               |                               |                               |                               |                 |            |        |             |              | <insufficient privilege>              | 
        |                    |  121 |          |          |                  |             |                 |             |                               |                               |                               |                               |                 |            |        |             |              | <insufficient privilege>              | 
(7 rows)

