meta_product_name: "Danny DeVeto"
meta_title: "Danny DeVeto - It won't change the world, but it will make choosing movies more fun!"
meta_description: "Why is your housemate taking so long to choose a movie?! Sofa-loving streamers always disagree about which TV show or movie to watch. Meanwhile their pizza is getting cold!"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@Danny_DeVeto"
